local M = {}

---@type theme_name.HighlightsFn
function M.get(c, opts)
	local ret = {

		["@comment"] = "Comment",
		["@keyword"] = "Statement",
		["@keyword.operator"] = { fg = c.subtle },
		["@keyword.return"] = "@keyword",
		["@string"] = "String",
		["@string.documentation"] = "@string",
		["@constant"] = "Constant",
		["@keyword.import"] = "Include",
		["@number"] = "Number",
		["@boolean"] = "Boolean",
		["@number.float"] = "Float",
		["@type"] = "Type",
		["@variable.member"] = "@variable",
		["@keyword.function"] = "@keyword",
		["@constructor"] = "Function",
		["@attribute"] = "PreProc",
		["@attribute.builtin"] = "@attribute",
		["@operator"] = "Operator",
		["@string.escape"] = "Character",
		["@function.builtin"] = "Special",
		["@function"] = "Function",
		["@type.definition"] = "Typedef",
		["@type.builtin"] = "@type",
		["@variable"] = { fg = c.fg },
		["@module"] = { fg = c.fg },
		["@punctuation.bracket"] = "Delimiter",
		["@punctuation.delimiter"] = { fg = c.subtle },
		["@variable.parameter"] = { fg = c.fg },
		["@constant.builtin"] = { fg = c.gild },
		["@annotation"] = "PreProc",
		["@character"] = "Character",
		["@character.printf"] = "SpecialChar",
		["@character.special"] = "SpecialChar",
		["@constant.macro"] = "@constant",
		["@function.call"] = "@function",
		["@function.macro"] = "Macro",
		["@function.method"] = "Function",
		["@function.method.call"] = "@function.method",
		["@keyword.conditional"] = "Conditional",
		["@keyword.debug"] = "Debug",
		["@keyword.directive"] = { fg = c.smoke, italic = true },
		["@keyword.directive.define"] = "Define",
		["@keyword.exception"] = "Exception",
		["@keyword.repeat"] = "Repeat",
		["@keyword.storage"] = "StorageClass",
		["@type.qualifier"] = "@keyword",
		["@namespace.builtin"] = "@variable.builtin",
		["@tag"] = "Label",
		["@tag.attribute"] = { fg = c.ichor },
		["@tag.delimiter"] = "Delimiter",
		["@diff.plus"] = "DiffAdd",
		["@diff.minus"] = "DiffDelete",
		["@diff.delta"] = "DiffChange",
		["@markup"] = "@none",
		["@markup.environment"] = "Macro",
		["@markup.environment.name"] = "Type",
		["@markup.heading"] = "Title",
		["@markup.link.label.symbol"] = "Identifier",
		["@markup.math"] = "Special",
		["@markup.raw"] = "String",
		["@property"] = { fg = c.fg },
		["@punctuation.special"] = { fg = c.subtle },
		["@none"] = {},
		["@variable.builtin"] = { fg = c.fg, italic = true },
		["@comment.nospell"] = { fg = c.smoke, italic = true },
		["@module.builtin"] = { fg = c.fg },
		["@markup.italic"] = { italic = true },
		["@markup.strong"] = { bold = true },
		["@markup.list"] = { fg = c.jade },
		["@markup.link.url"] = { fg = c.arcana, underline = true },
		["@markup.link.label"] = { fg = c.azure },
		["@markup.link"] = { fg = c.arcana },
		["@markup.list.checked"] = { fg = c.fg },
		["@markup.list.unchecked"] = { fg = c.fg_dim },
		["@markup.emphasis"] = { italic = true },
		["@markup.underline"] = { underline = true },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.raw.markdown_inline"] = { fg = c.ember },
		["@markup.list.markdown"] = { fg = c.jade, bold = true },
		["@markup.heading.1.markdown"] = { fg = c.jade },
		["@markup.heading.2.markdown"] = { fg = c.wyrm },
		["@markup.heading.3.markdown"] = { fg = c.azure },
		["@markup.heading.4.markdown"] = { fg = c.ember },
		["@markup.heading.5.markdown"] = { fg = c.arcana },
		["@markup.heading.6.markdown"] = { fg = c.gild },
		["@comment.error"] = { fg = c.error },
		["@comment.warning"] = { fg = c.warning },
		["@comment.info"] = { fg = c.info },
		["@comment.hint"] = { fg = c.hint },
		["@comment.note"] = { fg = c.hint },
		["@comment.todo"] = { fg = c.hint },
		["@string.regexp"] = { fg = c.arcana },
		["@constant.regexp"] = { fg = c.gild },
		["@punctuation.bracket.regexp"] = "Delimiter",
		["@label"] = { fg = c.jade }, -- Things outside code on Arcana?
		["@variable.parameter.builtin"] = { fg = c.fg },
		["@tag.tsx"] = { fg = c.jade },
		["@tag.javascript"] = { fg = c.jade },
		["@tag.builtin"] = { fg = c.jade },
		["@tag.delimiter.tsx"] = { fg = c.subtle },
		["@constructor.tsx"] = { fg = c.azure },
		["@punctuation.special.markdown"] = { fg = c.subtle },
	}

	return ret
end

return M
