# -----------------------------------------------------------------------------
# theme_name Alacritty Colors
# Theme: theme_name
# Upstream: https://github.com/nnahuel/ y file
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#181A1C'
foreground = '#E9F2F2'
dim_foreground = '#6E797E'
bright_foreground = '#F5FAFA'

# Cursor colors
[colors.cursor]
text = '#181A1C'
cursor = '#E9f2f2'

[colors.vi_mode_cursor]
text = '#E9F2F2'
cursor = '#1B1E20'

# Selection colors
[colors.selection]
text = 'CellForeground'
background = '#33383C'

# Normal colors
[colors.normal]
black = '#131618'
red = '#D04E63'
green = '#72C472'
yellow = '#EAD88A'
blue = '#9EDFE2'
magenta = '#B8A0D5'
cyan = '#5FB3A3'
white = '#E9F2F2'

# Bright colors
[colors.bright]
black = '#33383C'
red = '#F08090'
green = '#88E888'
yellow = '#FFF2B0'
blue = '#D0FFFF'
magenta = '#D8C5F0'
cyan = '#88E0D0'
white = '#F5FAFA'
