## name: theme_name
## author: Your Name
## license: MIT
## upstream: https://github.com/nnahuel/
## blurb: A minimalist dark theme for code editors and terminals

background               #181A1C
foreground               #E9F2F2
selection_foreground     #E9F2F2
selection_background     #33383C

cursor                   #E9F2F2
cursor_text_color        #181A1C

url_color                #EAD88A

active_tab_foreground    #E9F2F2
active_tab_background    #181A1C
inactive_tab_foreground  #6E797E
inactive_tab_background  #1F2225

active_border_color      #272C2F
inactive_border_color    #33383C

# black
color0   #131618
color8   #33383C

# red
color1   #D04E63
color9   #F08090

# green
color2   #72C472
color10  #88E888

# yellow
color3   #EAD88A
color11  #FFF2B0

# blue
color4   #9EDFE2
color12  #D0FFFF

# magenta
color5   #B8A0D5
color13  #D8C5F0

# cyan
color6   #5FB3A3
color14  #88E0D0

# white
color7   #E9F2F2
color15  #F5FAFA
